### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by koliapp2019** [fcakyon/face-recognition-app-tutorial#7]
After the fix, we encountered another error -

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /detect (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000001E29642AF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

Seems to be cause by this line -

response = requests.post('http://127.0.0.1:3000/detect', files={'image': image})

Shouldn't it be a port 4000? Also, how did you make it work on heroku with that hard coded port?

I am running from http://127.0.0.1:4000/upload for now.

**Comment by koliapp2019** [comment]
If we change the port to 4000 (the origin) port, another error will show up -

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by fcakyon** [comment]
@koliapp2019 please refer to [readme for usage](https://github.com/fcakyon/face-recognition-app-tutorial#app-usage)

you have to run [face detection app](https://github.com/fcakyon/face-detection-app-tutorial) in port 3000 so that you dont receive this error

**Comment by koliapp2019** [comment]
Like I said, another error is show -

    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Change to port 3000 as such -

if __name__ == '__main__':
    app.run(debug=True,
            use_reloader=True,
            port=3000)

**Comment by koliapp2019** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\XXX\kl\face-recognition-app-tutorial\app.py", line 40, in upload
    faces = recognize_faces(image, classifier_model_path, label_encoder_path)
  File "C:\Users\XXX\kl\face-recognition-app-tutorial\source\face_recognition.py", line 109, in recognize_faces
    detections = detect_faces(image)
  File "C:\Users\XXX\kl\face-recognition-app-tutorial\source\face_recognition.py", line 21, in detect_faces
    response_json = response.json()
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\requests\models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\XXX\.pyenv\pyenv-win\versions\3.6.8\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by fcakyon** [comment]
You should not change the port to 3000, [it should stay at 4000](https://github.com/fcakyon/face-recognition-app-tutorial/blob/5aaa78dfab6ce19672b1cb23fe03036dc2419b2b/app.py#L53). That is causing your error.

**Comment by koliapp2019** [comment]
Reverted to 4000. The error is the same -

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /detect (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000001B8428E4E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

The line 18 in face_recognition.py is -

    response = requests.post('http://127.0.0.1:3000/detect', files={'image': image})

**Comment by fcakyon** [comment]
Have you read the [app usage section in readme](https://github.com/fcakyon/face-recognition-app-tutorial#app-usage) ?

You should clone and run this project before: https://github.com/fcakyon/face-detection-app-tutorial

[Face Detection](https://github.com/fcakyon/face-detection-app-tutorial) and [Face Recognition](https://github.com/fcakyon/face-recognition-app-tutorial) apps are 2 seperate apps. You should first run the [Face Detection](https://github.com/fcakyon/face-detection-app-tutorial) app then run this [Face Recognition](https://github.com/fcakyon/face-recognition-app-tutorial) app. These two apps will communicate between each other in their respective ports (3000 and 4000).

**Comment by koliapp2019** [comment]
Why can't we run it in a single app?

**Comment by fcakyon** [comment]
I believe it is more modular and clean this way.

You can combine the models folder and app.py file to combine detection&recognition into single app.

**Comment by koliapp2019** [comment]
That fixed it. We will test heroku too.

Oh ya, if there is no face found, do you know why it gave this error?

TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(128, 32), dtype=float32) is not an element of this graph.

**Comment by fcakyon** [comment]
You should deploy detection and recognition apis as two seperate heroku apps and replace [this line](https://github.com/fcakyon/face-recognition-app-tutorial/blob/054abbd589b0f3b2278ddd3ffe62b1267304aeaa/source/face_recognition.py#L17) with your heroku api.

**Comment by fcakyon** [comment]
@koliapp2019 lets continue with a new issue thread https://github.com/fcakyon/face-recognition-app-tutorial/issues/8
